export enum FuzzySearchResultType {
    /** Point of Interest — named place (airport, restaurant, gas station, hotel, etc.) */
    POI = 'POI',

    /** Street — a road/street without a specific building number (e.g. "Marszałkowska St"). */
    STREET = 'Street',

    /** Point Address — exact address with street name and building number (e.g. "Soquel Dr 2501") */
    POINT_ADDRESS = 'Point Address',

    /** Geography — an administrative area: country, region, city, district or postal code area.
     *  @filtered - NOT RELEVANT */
    GEOGRAPHY = 'Geography',

    /** Address Range — interpolated address range on a street segment when an exact number is not indexed.
     *  @filtered - NOT RELEVANT */
    ADDRESS_RANGE = 'Address Range',

    /** Cross Street — a street intersection (e.g. "Main St at Oak Ave").
     *  @filtered - NOT RELEVANT */
    CROSS_STREET = 'Cross Street',

    /** Extended Postal Point — precise postal-code-level point used in UK, Ireland and the Netherlands.
     *  @filtered - NOT RELEVANT */
    EXTENDED_POSTAL_POINT = 'Extended Postal Point',
}


/**
 * `type` values that carry `@filtered` in {@link FuzzySearchResultType} JSDoc (excluded from UI).
 */
export const ENUM_JSDOC_FILTERED_FUZZY_TYPES = new Set<FuzzySearchResultType>([
    FuzzySearchResultType.GEOGRAPHY,
    FuzzySearchResultType.ADDRESS_RANGE,
    FuzzySearchResultType.CROSS_STREET,
    FuzzySearchResultType.EXTENDED_POSTAL_POINT,
])


/**
 * TomTom Search API — supported top-level POI category codes (service version 2).
 * @see https://developer.tomtom.com/search-api/documentation/product-information/supported-category-codes
 */
export enum LocationCategoryCodeEnum {
    ACCESS_GATEWAY = 'ACCESS_GATEWAY',
    ADMINISTRATIVE_DIVISION = 'ADMINISTRATIVE_DIVISION',
    ADVENTURE_SPORTS_VENUE = 'ADVENTURE_SPORTS_VENUE',
    AGRICULTURE = 'AGRICULTURE',
    AIRPORT = 'AIRPORT',
    AMUSEMENT_PARK = 'AMUSEMENT_PARK',
    AUTOMOTIVE_DEALER = 'AUTOMOTIVE_DEALER',
    BANK = 'BANK',
    BEACH = 'BEACH',
    BUILDING_POINT = 'BUILDING_POINT',
    BUSINESS_PARK = 'BUSINESS_PARK',
    CAFE_PUB = 'CAFE_PUB',
    CAMPING_GROUND = 'CAMPING_GROUND',
    CAR_WASH = 'CAR_WASH',
    CASH_DISPENSER = 'CASH_DISPENSER',
    CASINO = 'CASINO',
    CINEMA = 'CINEMA',
    CITY_CENTER = 'CITY_CENTER',
    CLUB_ASSOCIATION = 'CLUB_ASSOCIATION',
    COLLEGE_UNIVERSITY = 'COLLEGE_UNIVERSITY',
    COMMERCIAL_BUILDING = 'COMMERCIAL_BUILDING',
    COMMUNITY_CENTER = 'COMMUNITY_CENTER',
    COMPANY = 'COMPANY',
    COURTHOUSE = 'COURTHOUSE',
    CULTURAL_CENTER = 'CULTURAL_CENTER',
    DENTIST = 'DENTIST',
    DEPARTMENT_STORE = 'DEPARTMENT_STORE',
    DOCTOR = 'DOCTOR',
    ELECTRIC_VEHICLE_STATION = 'ELECTRIC_VEHICLE_STATION',
    EMBASSY = 'EMBASSY',
    EMERGENCY_MEDICAL_SERVICE = 'EMERGENCY_MEDICAL_SERVICE',
    ENTERTAINMENT = 'ENTERTAINMENT',
    EXCHANGE = 'EXCHANGE',
    EXHIBITION_CONVENTION_CENTER = 'EXHIBITION_CONVENTION_CENTER',
    FERRY_TERMINAL = 'FERRY_TERMINAL',
    FIRE_STATION_BRIGADE = 'FIRE_STATION_BRIGADE',
    FRONTIER_CROSSING = 'FRONTIER_CROSSING',
    FUEL_FACILITIES = 'FUEL_FACILITIES',
    GEOGRAPHIC_FEATURE = 'GEOGRAPHIC_FEATURE',
    GOLF_COURSE = 'GOLF_COURSE',
    GOVERNMENT_OFFICE = 'GOVERNMENT_OFFICE',
    HEALTH_CARE_SERVICE = 'HEALTH_CARE_SERVICE',
    HELIPAD_HELICOPTER_LANDING = 'HELIPAD_HELICOPTER_LANDING',
    HOLIDAY_RENTAL = 'HOLIDAY_RENTAL',
    HOSPITAL_POLYCLINIC = 'HOSPITAL_POLYCLINIC',
    HOTEL_MOTEL = 'HOTEL_MOTEL',
    ICE_SKATING_RINK = 'ICE_SKATING_RINK',
    IMPORTANT_TOURIST_ATTRACTION = 'IMPORTANT_TOURIST_ATTRACTION',
    INDUSTRIAL_BUILDING = 'INDUSTRIAL_BUILDING',
    LEISURE_CENTER = 'LEISURE_CENTER',
    LIBRARY = 'LIBRARY',
    MANUFACTURING_FACILITY = 'MANUFACTURING_FACILITY',
    MARINA = 'MARINA',
    MARKET = 'MARKET',
    MEDIA_FACILITY = 'MEDIA_FACILITY',
    MILITARY_INSTALLATION = 'MILITARY_INSTALLATION',
    MOTORING_ORGANIZATION_OFFICE = 'MOTORING_ORGANIZATION_OFFICE',
    MOUNTAIN_PASS = 'MOUNTAIN_PASS',
    MUSEUM = 'MUSEUM',
    NATIVE_RESERVATION = 'NATIVE_RESERVATION',
    NIGHTLIFE = 'NIGHTLIFE',
    NON_GOVERNMENTAL_ORGANIZATION = 'NON_GOVERNMENTAL_ORGANIZATION',
    OPEN_PARKING_AREA = 'OPEN_PARKING_AREA',
    OTHER = 'OTHER',
    PARKING_GARAGE = 'PARKING_GARAGE',
    PARK_RECREATION_AREA = 'PARK_RECREATION_AREA',
    PETROL_STATION = 'PETROL_STATION',
    PHARMACY = 'PHARMACY',
    PLACE_OF_WORSHIP = 'PLACE_OF_WORSHIP',
    POLICE_STATION = 'POLICE_STATION',
    PORT_WAREHOUSE_FACILITY = 'PORT_WAREHOUSE_FACILITY',
    POST_OFFICE = 'POST_OFFICE',
    PRIMARY_RESOURCE_UTILITY = 'PRIMARY_RESOURCE_UTILITY',
    PRISON_CORRECTIONAL_FACILITY = 'PRISON_CORRECTIONAL_FACILITY',
    PUBLIC_AMENITY = 'PUBLIC_AMENITY',
    PUBLIC_TRANSPORT_STOP = 'PUBLIC_TRANSPORT_STOP',
    RAILWAY_STATION = 'RAILWAY_STATION',
    RENT_A_CAR_FACILITY = 'RENT_A_CAR_FACILITY',
    RENT_A_CAR_PARKING = 'RENT_A_CAR_PARKING',
    REPAIR_FACILITY = 'REPAIR_FACILITY',
    RESEARCH_FACILITY = 'RESEARCH_FACILITY',
    RESIDENTIAL_ACCOMMODATION = 'RESIDENTIAL_ACCOMMODATION',
    RESTAURANT = 'RESTAURANT',
    RESTAURANT_AREA = 'RESTAURANT_AREA',
    REST_AREA = 'REST_AREA',
    SCENIC_PANORAMIC_VIEW = 'SCENIC_PANORAMIC_VIEW',
    SCHOOL = 'SCHOOL',
    SHOP = 'SHOP',
    SHOPPING_CENTER = 'SHOPPING_CENTER',
    SPORTS_CENTER = 'SPORTS_CENTER',
    STADIUM = 'STADIUM',
    SWIMMING_POOL = 'SWIMMING_POOL',
    TENNIS_COURT = 'TENNIS_COURT',
    THEATER = 'THEATER',
    TOURIST_INFORMATION_OFFICE = 'TOURIST_INFORMATION_OFFICE',
    TRAFFIC_LIGHT = 'TRAFFIC_LIGHT',
    TRAFFIC_SERVICE_CENTER = 'TRAFFIC_SERVICE_CENTER',
    TRAFFIC_SIGN = 'TRAFFIC_SIGN',
    TRAIL_SYSTEM = 'TRAIL_SYSTEM',
    TRANSPORT_AUTHORITY_VEHICLE_REGISTRATION = 'TRANSPORT_AUTHORITY_VEHICLE_REGISTRATION',
    TRUCK_STOP = 'TRUCK_STOP',
    VETERINARIAN = 'VETERINARIAN',
    WATER_SPORT = 'WATER_SPORT',
    WEIGH_STATION = 'WEIGH_STATION',
    WELFARE_ORGANIZATION = 'WELFARE_ORGANIZATION',
    WINERY = 'WINERY',
    ZOOS_ARBORETA_BOTANICAL_GARDEN = 'ZOOS_ARBORETA_BOTANICAL_GARDEN',
}